config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true
    validates :softness, presence: true
    validates :cuteness, presence: true
    validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ActionController::Base
    def index
        @kittens = Kitten.all 
        respond_to do |format|
            format.html
            format.json { render :json => @kittens }
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params)
        respond_to do |format|
            if @kitten.save
                format.html { redirect_to @kitten, notice: "You created a new kitten!" }
            else
                format.html { render :new, notice: "You messed up! Try again." }
            end
        end
    end

    def show
        @kitten = Kitten.find(params[:id])
        respond_to do |format|
            format.html
            format.json { render :json => @kitten }
        end
    end

    def edit
        @kitten = Kitten.find(params[:id])        
    end

    def update
        @kitten = Kitten.find(params[:id])
        @kitten.update(name: params[:kitten][:name], age: params[:kitten][:age], cuteness: params[:kitten][:cuteness], softness: params[:kitten][:softness])
        redirect_to @kitten, notice: "Kitten successfully updated."
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: "Kitten successfully deleted." }
        end
    end

    private

    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :softness %>
    <%= f.select :softness, options_for_select((1..10)) %>
    <%= f.label :cuteness %>
    <%= f.select :cuteness, options_for_select((1..10)) %>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>

<%= render "form" %>

<%= button_to "Delete", @kitten, :method => :delete %>

app/views/kittens/index.html.erb
<h1>All kittens</h1>

<% @kittens.each do |kitten| %>
    <h2><%= kitten.name %></h2>
    <b><p>Age:</p></b>
    <p><%= kitten.age %></p>
    <b><p>Softness:</p></b>
    <p><%= kitten.softness %></p>
    <b><p>Cuteness:</p></b>
    <p><%= kitten.cuteness %></p>
    <%= button_to "Delete", kitten, :method => :delete %>
    <%= link_to "Edit", edit_kitten_url(kitten) %>
<% end %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render "form" %>

app/views/kittens/show.html.erb
<%= notice %>

<h2><%= @kitten.name %></h2>

<b><p>Cuteness:</p></b>
<%= @kitten.cuteness %>

<b><p>Age:</p></b>
<%= @kitten.age %>

<b><p>Softness:</p></b>
<%= @kitten.softness %></br></br>

<%= button_to "Delete", @kitten, :method => :delete %>

<%= link_to "Edit", edit_kitten_url(@kitten) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>